'use client'; import React from 'react';
import { motion } from 'framer-motion';
import { Code, Copy } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link'; export default function CreateDesignPage() { const exampleCode = `const response = await fetch('https://api.luneo.app/v1/designs', { method: 'POST', headers: { 'Authorization': 'Bearer YOUR_API_KEY', 'Content-Type': 'application/json' }, body: JSON.stringify({ productId: 'prod_123', prompt: 'Créer un logo moderne pour une startup tech', options: { style: 'modern', colors: ['#3B82F6', '#8B5CF6'], format: 'png' } })
}); const design = await response.json();
console.log('Design créé:', design.id);`; return ( <div className="min-h-screen bg-gray-900 text-white p-4 sm:p-6 md:p-4 sm:p-6 md:p-8"> <div className="max-w-4xl px-4 sm:px-6 mx-auto"> <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}> <div className="flex items-center text-sm text-gray-400 mb-6"> <Link href="/help/documentation" className="hover:text-white">Documentation</Link> <span className="mx-2">›</span> <Link href="/help/documentation/api-reference" className="hover:text-white">API Reference</Link> <span className="mx-2">›</span> <span className="text-white">Créer un design</span> </div> <h1 className="text-4xl md:text-3xl sm:text-2xl sm:text-xl sm:text-lg sm:text-xl md:text-2xl md:text-3xl md:text-4xl md:text-3xl sm:text-2xl sm:text-xl sm:text-lg sm:text-xl md:text-2xl md:text-3xl md:text-4xl md:text-2xl sm:text-3xl md:text-xl sm:text-2xl md:text-lg sm:text-xl md:text-2xl lg:text-3xl lg:text-4xl lg:text-xl min-[480px]:text-2xl sm:text-3xl md:text-4xl lg:text-xl sm:text-2xl md:text-lg min-[480px]:text-xl sm:text-2xl md:text-3xl lg:text-4xl xl:text-base min-[480px]:text-lg sm:text-xl md:text-2xl lg:text-base min-[480px]:text-lg sm:text-xl md:text-base min-[480px]:text-lg sm:text-xl md:text-2xl lg:text-3xl xl:text-2xl sm:text-3xl md:text-xl sm:text-2xl md:text-lg sm:text-xl md:text-2xl lg:text-3xl lg:text-4xl lg:text-2xl sm:text-3xl md:text-xl sm:text-2xl md:text-lg sm:text-xl md:text-2xl lg:text-3xl lg:text-4xl lg:text-5xl font-bold mb-4">Créer un Design</h1> <p className="text-xl text-gray-300 mb-12"> Apprenez à créer des designs personnalisés avec l'API Luneo. </p> <Card className="bg-gray-800 border-gray-700 p-6 mb-8"> <div className="flex flex-col sm:flex-row items-center justify-start sm:justify-between gap-3 sm:gap-0 mb-4"> <h3 className="text-lg font-semibold flex items-center"> <Code className="w-5 h-5 mr-2" /> Exemple de code </h3> <Button variant="outline" size="sm" className="border-cyan-500 text-cyan-400 hover:bg-cyan-500 hover:text-white"> <Copy className="w-4 h-4 mr-2" /> Copier </Button> </div> <pre className="bg-gray-900 rounded p-4 overflow-x-autooverflow-x-autooverflow-x-auto"> <code className="text-sm text-gray-300">{exampleCode}</code> </pre> </Card> <div className="prose prose-invert max-w-none"> <h2 className="text-lg sm:text-xl md:text-lg sm:text-xl md:text-base min-[480px]:text-lg sm:text-xl md:text-2xl font-bold mt-8 mb-4">Paramètres</h2> <ul className="space-y-4"> <li className="text-gray-300"> <strong className="text-white">productId</strong> (string, requis) - L'ID du produit à personnaliser </li> <li className="text-gray-300"> <strong className="text-white">prompt</strong> (string, requis) - Description du design souhaité </li> <li className="text-gray-300"> <strong className="text-white">options</strong> (object, optionnel) - Options de personnalisation </li> </ul> </div> </motion.div> </div> </div> );
}
