'use client'; import React from 'react';
import { DocPageTemplate } from '@/components/docs/DocPageTemplate';
import { Code, Copy } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button'; export default function JsSDKPage() { const installCode = `npm install @luneo/sdk`; const exampleCode = `import { LuneoClient } from '@luneo/sdk'; const client = new LuneoClient({ apiKey: 'your-api-key'
}); // Créer un design
const design = await client.designs.create({ productId: 'prod_123', prompt: 'Logo moderne pour startup tech'
}); console.log('Design créé:', design.id);`; return ( <DocPageTemplate title="SDK JavaScript" description="Utilisez notre SDK officiel pour JavaScript/TypeScript" breadcrumbs={[ { label: 'Documentation', href: '/help/documentation' }, { label: 'API Reference', href: '/help/documentation/api-reference' }, { label: 'SDK JavaScript', href: '/help/documentation/api-reference/js-sdk' } ]} relatedLinks={[ { title: 'API Reference', href: '/help/documentation/api-reference', description: 'Documentation complète de l\'API' }, { title: 'Exemples', href: '/help/documentation/api-reference/create-design', description: 'Exemples de code' } ]} > <h2 className="text-xl sm:text-lg sm:text-xl md:text-2xl md:text-xl sm:text-lg sm:text-xl md:text-2xl md:text-lg sm:text-xl md:text-2xl lg:text-xl sm:text-2xl md:text-base min-[480px]:text-lg sm:text-xl md:text-base min-[480px]:text-lg sm:text-xl md:text-2xl lg:text-lg sm:text-xl md:text-2xl lg:text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold mt-8 mb-4">Installation</h2> <Card className="bg-gray-800 border-gray-700 p-6 my-6"> <pre className="bg-gray-900 rounded p-4overflow-x-autooverflow-x-auto"> <code className="text-sm text-gray-300">{installCode}</code> </pre> </Card> <h2 className="text-xl sm:text-lg sm:text-xl md:text-2xl md:text-xl sm:text-lg sm:text-xl md:text-2xl md:text-lg sm:text-xl md:text-2xl lg:text-xl sm:text-2xl md:text-base min-[480px]:text-lg sm:text-xl md:text-base min-[480px]:text-lg sm:text-xl md:text-2xl lg:text-lg sm:text-xl md:text-2xl lg:text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold mt-8 mb-4">Utilisation</h2> <Card className="bg-gray-800 border-gray-700 p-6 my-6"> <div className="flex flex-col sm:flex-row items-center justify-start sm:justify-between gap-3 sm:gap-0 mb-4"> <h3 className="text-lg font-semibold flex items-center"> <Code className="w-5 h-5 mr-2" /> Exemple de code </h3> <Button variant="outline" size="sm" className="border-orange-500 text-orange-400 hover:bg-orange-500 hover:text-white"> <Copy className="w-4 h-4 mr-2" /> Copier </Button> </div> <pre className="bg-gray-900 rounded p-4 overflow-x-autooverflow-x-autooverflow-x-auto"> <code className="text-sm text-gray-300">{exampleCode}</code> </pre> </Card> <h2 className="text-xl sm:text-lg sm:text-xl md:text-2xl md:text-xl sm:text-lg sm:text-xl md:text-2xl md:text-lg sm:text-xl md:text-2xl lg:text-xl sm:text-2xl md:text-base min-[480px]:text-lg sm:text-xl md:text-base min-[480px]:text-lg sm:text-xl md:text-2xl lg:text-lg sm:text-xl md:text-2xl lg:text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold mt-8 mb-4">Fonctionnalités</h2> <ul className="space-y-2"> <li>✅ Support TypeScript natif</li> <li>✅ Gestion automatique des tokens</li> <li>✅ Retry automatique en cas d'erreur</li> <li>✅ Typages complets</li> </ul> </DocPageTemplate> );
}
