packages:
  - 'apps/frontend'
  - 'apps/backend'
  - 'packages/types'
  - 'packages/sdk'
  - 'packages/ai-safety'
  - 'packages/ar-engine'
  - 'packages/ar-export'
  - 'packages/optimization'
  - 'packages/bulk-generator'
  - 'packages/ui'
  - 'packages/virtual-try-on'
  - 'packages/billing-plans'
  - 'packages/widget'
