-- =====================================================
-- SEED CLIPARTS (50 cliparts SVG de base)
-- =====================================================

-- Animals
INSERT INTO public.cliparts (name, slug, description, category, subcategory, svg_url, preview_url, thumbnail_url, svg_viewbox, width, height, is_premium, is_featured, is_colorizable, default_color, tags, keywords, style, price) VALUES
('Dog Silhouette', 'dog-silhouette', 'Simple dog silhouette icon', 'Animals', 'Pets', 'https://www.svgrepo.com/show/13671/dog.svg', 'https://www.svgrepo.com/show/13671/dog.svg', 'https://www.svgrepo.com/show/13671/dog.svg', '0 0 512 512', 512, 512, false, true, true, '#000000', ARRAY['dog', 'pet', 'animal'], ARRAY['dog', 'pet', 'puppy'], 'Minimalist', 0),
('Cat Silhouette', 'cat-silhouette', 'Elegant cat silhouette icon', 'Animals', 'Pets', 'https://www.svgrepo.com/show/13671/cat.svg', 'https://www.svgrepo.com/show/13671/cat.svg', 'https://www.svgrepo.com/show/13671/cat.svg', '0 0 512 512', 512, 512, false, true, true, '#000000', ARRAY['cat', 'pet', 'animal'], ARRAY['cat', 'pet', 'kitten'], 'Minimalist', 0),
('Bird Flying', 'bird-flying', 'Flying bird icon', 'Animals', 'Wild', 'https://www.svgrepo.com/show/13671/bird.svg', 'https://www.svgrepo.com/show/13671/bird.svg', 'https://www.svgrepo.com/show/13671/bird.svg', '0 0 512 512', 512, 512, false, false, true, '#2563eb', ARRAY['bird', 'flying', 'animal'], ARRAY['bird', 'fly', 'nature'], 'Minimalist', 0),
('Butterfly', 'butterfly', 'Beautiful butterfly icon', 'Animals', 'Insects', 'https://www.svgrepo.com/show/13671/butterfly.svg', 'https://www.svgrepo.com/show/13671/butterfly.svg', 'https://www.svgrepo.com/show/13671/butterfly.svg', '0 0 512 512', 512, 512, false, true, true, '#ec4899', ARRAY['butterfly', 'insect', 'nature'], ARRAY['butterfly', 'insect', 'spring'], 'Hand-drawn', 0),
('Fish', 'fish', 'Simple fish icon', 'Animals', 'Aquatic', 'https://www.svgrepo.com/show/13671/fish.svg', 'https://www.svgrepo.com/show/13671/fish.svg', 'https://www.svgrepo.com/show/13671/fish.svg', '0 0 512 512', 512, 512, false, false, true, '#0ea5e9', ARRAY['fish', 'aquatic', 'animal'], ARRAY['fish', 'water', 'ocean'], 'Minimalist', 0);

-- Food
INSERT INTO public.cliparts (name, slug, description, category, subcategory, svg_url, preview_url, thumbnail_url, svg_viewbox, width, height, is_premium, is_featured, is_colorizable, default_color, has_multiple_colors, tags, keywords, style, price) VALUES
('Pizza Slice', 'pizza-slice', 'Delicious pizza slice', 'Food', 'Fast Food', 'https://www.svgrepo.com/show/13671/pizza.svg', 'https://www.svgrepo.com/show/13671/pizza.svg', 'https://www.svgrepo.com/show/13671/pizza.svg', '0 0 512 512', 512, 512, false, true, true, '#fbbf24', true, ARRAY['pizza', 'food', 'italian'], ARRAY['pizza', 'food', 'slice'], 'Modern', 0),
('Coffee Cup', 'coffee-cup', 'Hot coffee cup icon', 'Food', 'Beverages', 'https://www.svgrepo.com/show/13671/coffee.svg', 'https://www.svgrepo.com/show/13671/coffee.svg', 'https://www.svgrepo.com/show/13671/coffee.svg', '0 0 512 512', 512, 512, false, true, true, '#78350f', false, ARRAY['coffee', 'beverage', 'drink'], ARRAY['coffee', 'cup', 'cafe'], 'Minimalist', 0),
('Ice Cream Cone', 'ice-cream-cone', 'Sweet ice cream cone', 'Food', 'Desserts', 'https://www.svgrepo.com/show/13671/ice-cream.svg', 'https://www.svgrepo.com/show/13671/ice-cream.svg', 'https://www.svgrepo.com/show/13671/ice-cream.svg', '0 0 512 512', 512, 512, false, false, true, '#f472b6', true, ARRAY['ice cream', 'dessert', 'sweet'], ARRAY['ice cream', 'cone', 'dessert'], 'Hand-drawn', 0),
('Burger', 'burger', 'Classic burger icon', 'Food', 'Fast Food', 'https://www.svgrepo.com/show/13671/burger.svg', 'https://www.svgrepo.com/show/13671/burger.svg', 'https://www.svgrepo.com/show/13671/burger.svg', '0 0 512 512', 512, 512, false, true, true, '#f97316', true, ARRAY['burger', 'food', 'fast food'], ARRAY['burger', 'hamburger', 'food'], 'Modern', 0),
('Cupcake', 'cupcake', 'Cute cupcake icon', 'Food', 'Desserts', 'https://www.svgrepo.com/show/13671/cupcake.svg', 'https://www.svgrepo.com/show/13671/cupcake.svg', 'https://www.svgrepo.com/show/13671/cupcake.svg', '0 0 512 512', 512, 512, true, true, true, '#ec4899', true, ARRAY['cupcake', 'dessert', 'sweet'], ARRAY['cupcake', 'cake', 'dessert'], 'Hand-drawn', 2.99);

-- Nature
INSERT INTO public.cliparts (name, slug, description, category, subcategory, svg_url, preview_url, thumbnail_url, svg_viewbox, width, height, is_premium, is_featured, is_colorizable, default_color, tags, keywords, style, price) VALUES
('Tree', 'tree', 'Simple tree icon', 'Nature', 'Plants', 'https://www.svgrepo.com/show/13671/tree.svg', 'https://www.svgrepo.com/show/13671/tree.svg', 'https://www.svgrepo.com/show/13671/tree.svg', '0 0 512 512', 512, 512, false, true, true, '#15803d', ARRAY['tree', 'nature', 'plant'], ARRAY['tree', 'forest', 'nature'], 'Minimalist', 0),
('Flower', 'flower', 'Beautiful flower icon', 'Nature', 'Plants', 'https://www.svgrepo.com/show/13671/flower.svg', 'https://www.svgrepo.com/show/13671/flower.svg', 'https://www.svgrepo.com/show/13671/flower.svg', '0 0 512 512', 512, 512, false, true, true, '#ec4899', ARRAY['flower', 'nature', 'plant'], ARRAY['flower', 'bloom', 'spring'], 'Hand-drawn', 0),
('Sun', 'sun', 'Bright sun icon', 'Nature', 'Weather', 'https://www.svgrepo.com/show/13671/sun.svg', 'https://www.svgrepo.com/show/13671/sun.svg', 'https://www.svgrepo.com/show/13671/sun.svg', '0 0 512 512', 512, 512, false, true, true, '#fbbf24', ARRAY['sun', 'weather', 'nature'], ARRAY['sun', 'sunny', 'weather'], 'Modern', 0),
('Moon', 'moon', 'Crescent moon icon', 'Nature', 'Weather', 'https://www.svgrepo.com/show/13671/moon.svg', 'https://www.svgrepo.com/show/13671/moon.svg', 'https://www.svgrepo.com/show/13671/moon.svg', '0 0 512 512', 512, 512, false, false, true, '#6366f1', ARRAY['moon', 'night', 'nature'], ARRAY['moon', 'night', 'weather'], 'Minimalist', 0),
('Star', 'star', 'Five-pointed star', 'Nature', 'Sky', 'https://www.svgrepo.com/show/13671/star.svg', 'https://www.svgrepo.com/show/13671/star.svg', 'https://www.svgrepo.com/show/13671/star.svg', '0 0 512 512', 512, 512, false, true, true, '#fbbf24', ARRAY['star', 'sky', 'nature'], ARRAY['star', 'night', 'shine'], 'Modern', 0);

-- Technology
INSERT INTO public.cliparts (name, slug, description, category, subcategory, svg_url, preview_url, thumbnail_url, svg_viewbox, width, height, is_premium, is_featured, is_colorizable, default_color, tags, keywords, style, price) VALUES
('Laptop', 'laptop', 'Modern laptop icon', 'Technology', 'Computers', 'https://www.svgrepo.com/show/13671/laptop.svg', 'https://www.svgrepo.com/show/13671/laptop.svg', 'https://www.svgrepo.com/show/13671/laptop.svg', '0 0 512 512', 512, 512, false, true, true, '#3b82f6', ARRAY['laptop', 'computer', 'tech'], ARRAY['laptop', 'computer', 'technology'], 'Minimalist', 0),
('Smartphone', 'smartphone', 'Mobile phone icon', 'Technology', 'Mobile', 'https://www.svgrepo.com/show/13671/smartphone.svg', 'https://www.svgrepo.com/show/13671/smartphone.svg', 'https://www.svgrepo.com/show/13671/smartphone.svg', '0 0 512 512', 512, 512, false, true, true, '#000000', ARRAY['smartphone', 'mobile', 'tech'], ARRAY['smartphone', 'phone', 'mobile'], 'Modern', 0),
('Camera', 'camera', 'Professional camera icon', 'Technology', 'Photography', 'https://www.svgrepo.com/show/13671/camera.svg', 'https://www.svgrepo.com/show/13671/camera.svg', 'https://www.svgrepo.com/show/13671/camera.svg', '0 0 512 512', 512, 512, false, false, true, '#000000', ARRAY['camera', 'photo', 'tech'], ARRAY['camera', 'photography', 'photo'], 'Minimalist', 0),
('Headphones', 'headphones', 'Music headphones icon', 'Technology', 'Audio', 'https://www.svgrepo.com/show/13671/headphones.svg', 'https://www.svgrepo.com/show/13671/headphones.svg', 'https://www.svgrepo.com/show/13671/headphones.svg', '0 0 512 512', 512, 512, false, true, true, '#3b82f6', ARRAY['headphones', 'audio', 'music'], ARRAY['headphones', 'music', 'audio'], 'Modern', 0),
('Rocket', 'rocket', 'Space rocket icon', 'Technology', 'Space', 'https://www.svgrepo.com/show/13671/rocket.svg', 'https://www.svgrepo.com/show/13671/rocket.svg', 'https://www.svgrepo.com/show/13671/rocket.svg', '0 0 512 512', 512, 512, true, true, true, '#ef4444', ARRAY['rocket', 'space', 'tech'], ARRAY['rocket', 'space', 'launch'], 'Modern', 1.99);

-- Business
INSERT INTO public.cliparts (name, slug, description, category, subcategory, svg_url, preview_url, thumbnail_url, svg_viewbox, width, height, is_premium, is_featured, is_colorizable, default_color, tags, keywords, style, price) VALUES
('Briefcase', 'briefcase', 'Professional briefcase icon', 'Business', 'Office', 'https://www.svgrepo.com/show/13671/briefcase.svg', 'https://www.svgrepo.com/show/13671/briefcase.svg', 'https://www.svgrepo.com/show/13671/briefcase.svg', '0 0 512 512', 512, 512, false, true, true, '#1e40af', ARRAY['briefcase', 'business', 'office'], ARRAY['briefcase', 'work', 'business'], 'Minimalist', 0),
('Chart Growth', 'chart-growth', 'Growth chart icon', 'Business', 'Analytics', 'https://www.svgrepo.com/show/13671/chart.svg', 'https://www.svgrepo.com/show/13671/chart.svg', 'https://www.svgrepo.com/show/13671/chart.svg', '0 0 512 512', 512, 512, false, true, true, '#15803d', ARRAY['chart', 'growth', 'business'], ARRAY['chart', 'analytics', 'growth'], 'Modern', 0),
('Light Bulb', 'light-bulb', 'Idea light bulb icon', 'Business', 'Innovation', 'https://www.svgrepo.com/show/13671/bulb.svg', 'https://www.svgrepo.com/show/13671/bulb.svg', 'https://www.svgrepo.com/show/13671/bulb.svg', '0 0 512 512', 512, 512, false, true, true, '#fbbf24', ARRAY['bulb', 'idea', 'innovation'], ARRAY['bulb', 'idea', 'light'], 'Minimalist', 0),
('Target', 'target', 'Business target icon', 'Business', 'Goals', 'https://www.svgrepo.com/show/13671/target.svg', 'https://www.svgrepo.com/show/13671/target.svg', 'https://www.svgrepo.com/show/13671/target.svg', '0 0 512 512', 512, 512, false, false, true, '#ef4444', ARRAY['target', 'goal', 'business'], ARRAY['target', 'goal', 'aim'], 'Modern', 0),
('Handshake', 'handshake', 'Business handshake icon', 'Business', 'Partnership', 'https://www.svgrepo.com/show/13671/handshake.svg', 'https://www.svgrepo.com/show/13671/handshake.svg', 'https://www.svgrepo.com/show/13671/handshake.svg', '0 0 512 512', 512, 512, true, true, true, '#3b82f6', ARRAY['handshake', 'partnership', 'business'], ARRAY['handshake', 'deal', 'partnership'], 'Minimalist', 2.99);

-- Holidays
INSERT INTO public.cliparts (name, slug, description, category, subcategory, svg_url, preview_url, thumbnail_url, svg_viewbox, width, height, is_premium, is_featured, is_colorizable, default_color, has_multiple_colors, tags, keywords, style, price) VALUES
('Christmas Tree', 'christmas-tree', 'Festive Christmas tree', 'Holidays', 'Christmas', 'https://www.svgrepo.com/show/13671/christmas-tree.svg', 'https://www.svgrepo.com/show/13671/christmas-tree.svg', 'https://www.svgrepo.com/show/13671/christmas-tree.svg', '0 0 512 512', 512, 512, false, true, true, '#15803d', true, ARRAY['christmas', 'holiday', 'tree'], ARRAY['christmas', 'tree', 'holiday'], 'Hand-drawn', 0),
('Gift Box', 'gift-box', 'Present gift box', 'Holidays', 'General', 'https://www.svgrepo.com/show/13671/gift.svg', 'https://www.svgrepo.com/show/13671/gift.svg', 'https://www.svgrepo.com/show/13671/gift.svg', '0 0 512 512', 512, 512, false, true, true, '#ef4444', true, ARRAY['gift', 'present', 'holiday'], ARRAY['gift', 'present', 'box'], 'Modern', 0),
('Heart', 'heart', 'Love heart icon', 'Holidays', 'Valentine', 'https://www.svgrepo.com/show/13671/heart.svg', 'https://www.svgrepo.com/show/13671/heart.svg', 'https://www.svgrepo.com/show/13671/heart.svg', '0 0 512 512', 512, 512, false, true, true, '#ec4899', false, ARRAY['heart', 'love', 'valentine'], ARRAY['heart', 'love', 'valentine'], 'Minimalist', 0),
('Pumpkin', 'pumpkin', 'Halloween pumpkin', 'Holidays', 'Halloween', 'https://www.svgrepo.com/show/13671/pumpkin.svg', 'https://www.svgrepo.com/show/13671/pumpkin.svg', 'https://www.svgrepo.com/show/13671/pumpkin.svg', '0 0 512 512', 512, 512, false, false, true, '#f97316', false, ARRAY['pumpkin', 'halloween', 'holiday'], ARRAY['pumpkin', 'halloween', 'spooky'], 'Hand-drawn', 0),
('Fireworks', 'fireworks', 'Celebration fireworks', 'Holidays', 'New Year', 'https://www.svgrepo.com/show/13671/fireworks.svg', 'https://www.svgrepo.com/show/13671/fireworks.svg', 'https://www.svgrepo.com/show/13671/fireworks.svg', '0 0 512 512', 512, 512, true, true, true, '#fbbf24', true, ARRAY['fireworks', 'celebration', 'new year'], ARRAY['fireworks', 'celebration', 'party'], 'Modern', 1.99);

-- Sports
INSERT INTO public.cliparts (name, slug, description, category, subcategory, svg_url, preview_url, thumbnail_url, svg_viewbox, width, height, is_premium, is_featured, is_colorizable, default_color, tags, keywords, style, price) VALUES
('Soccer Ball', 'soccer-ball', 'Classic soccer ball', 'Sports', 'Football', 'https://www.svgrepo.com/show/13671/soccer.svg', 'https://www.svgrepo.com/show/13671/soccer.svg', 'https://www.svgrepo.com/show/13671/soccer.svg', '0 0 512 512', 512, 512, false, true, true, '#000000', ARRAY['soccer', 'football', 'sports'], ARRAY['soccer', 'ball', 'football'], 'Minimalist', 0),
('Basketball', 'basketball', 'Orange basketball', 'Sports', 'Basketball', 'https://www.svgrepo.com/show/13671/basketball.svg', 'https://www.svgrepo.com/show/13671/basketball.svg', 'https://www.svgrepo.com/show/13671/basketball.svg', '0 0 512 512', 512, 512, false, true, true, '#f97316', ARRAY['basketball', 'sports', 'ball'], ARRAY['basketball', 'ball', 'sport'], 'Modern', 0),
('Tennis Racket', 'tennis-racket', 'Tennis racket icon', 'Sports', 'Tennis', 'https://www.svgrepo.com/show/13671/tennis.svg', 'https://www.svgrepo.com/show/13671/tennis.svg', 'https://www.svgrepo.com/show/13671/tennis.svg', '0 0 512 512', 512, 512, false, false, true, '#15803d', ARRAY['tennis', 'sports', 'racket'], ARRAY['tennis', 'racket', 'sport'], 'Minimalist', 0),
('Dumbbell', 'dumbbell', 'Fitness dumbbell', 'Sports', 'Fitness', 'https://www.svgrepo.com/show/13671/dumbbell.svg', 'https://www.svgrepo.com/show/13671/dumbbell.svg', 'https://www.svgrepo.com/show/13671/dumbbell.svg', '0 0 512 512', 512, 512, false, true, true, '#3b82f6', ARRAY['dumbbell', 'fitness', 'gym'], ARRAY['dumbbell', 'workout', 'gym'], 'Modern', 0),
('Trophy', 'trophy', 'Winner trophy icon', 'Sports', 'Awards', 'https://www.svgrepo.com/show/13671/trophy.svg', 'https://www.svgrepo.com/show/13671/trophy.svg', 'https://www.svgrepo.com/show/13671/trophy.svg', '0 0 512 512', 512, 512, true, true, true, '#fbbf24', ARRAY['trophy', 'winner', 'award'], ARRAY['trophy', 'winner', 'champion'], 'Modern', 2.99);

-- Music & Art
INSERT INTO public.cliparts (name, slug, description, category, subcategory, svg_url, preview_url, thumbnail_url, svg_viewbox, width, height, is_premium, is_featured, is_colorizable, default_color, tags, keywords, style, price) VALUES
('Music Note', 'music-note', 'Musical note icon', 'Music', 'Notes', 'https://www.svgrepo.com/show/13671/music.svg', 'https://www.svgrepo.com/show/13671/music.svg', 'https://www.svgrepo.com/show/13671/music.svg', '0 0 512 512', 512, 512, false, true, true, '#000000', ARRAY['music', 'note', 'sound'], ARRAY['music', 'note', 'melody'], 'Minimalist', 0),
('Guitar', 'guitar', 'Electric guitar icon', 'Music', 'Instruments', 'https://www.svgrepo.com/show/13671/guitar.svg', 'https://www.svgrepo.com/show/13671/guitar.svg', 'https://www.svgrepo.com/show/13671/guitar.svg', '0 0 512 512', 512, 512, false, true, true, '#dc2626', ARRAY['guitar', 'music', 'instrument'], ARRAY['guitar', 'music', 'rock'], 'Modern', 0),
('Paint Brush', 'paint-brush', 'Artist paint brush', 'Art', 'Tools', 'https://www.svgrepo.com/show/13671/brush.svg', 'https://www.svgrepo.com/show/13671/brush.svg', 'https://www.svgrepo.com/show/13671/brush.svg', '0 0 512 512', 512, 512, false, false, true, '#3b82f6', ARRAY['brush', 'art', 'paint'], ARRAY['brush', 'paint', 'art'], 'Hand-drawn', 0),
('Palette', 'palette', 'Artist color palette', 'Art', 'Tools', 'https://www.svgrepo.com/show/13671/palette.svg', 'https://www.svgrepo.com/show/13671/palette.svg', 'https://www.svgrepo.com/show/13671/palette.svg', '0 0 512 512', 512, 512, false, true, true, '#ec4899', ARRAY['palette', 'art', 'color'], ARRAY['palette', 'color', 'art'], 'Modern', 0),
('Microphone', 'microphone', 'Recording microphone', 'Music', 'Equipment', 'https://www.svgrepo.com/show/13671/microphone.svg', 'https://www.svgrepo.com/show/13671/microphone.svg', 'https://www.svgrepo.com/show/13671/microphone.svg', '0 0 512 512', 512, 512, true, true, true, '#000000', ARRAY['microphone', 'music', 'recording'], ARRAY['microphone', 'mic', 'audio'], 'Minimalist', 1.99);

-- Icons (Common UI)
INSERT INTO public.cliparts (name, slug, description, category, subcategory, svg_url, preview_url, thumbnail_url, svg_viewbox, width, height, is_premium, is_featured, is_colorizable, default_color, tags, keywords, style, price) VALUES
('Check Mark', 'check-mark', 'Success check mark', 'Icons', 'Status', 'https://www.svgrepo.com/show/13671/check.svg', 'https://www.svgrepo.com/show/13671/check.svg', 'https://www.svgrepo.com/show/13671/check.svg', '0 0 512 512', 512, 512, false, true, true, '#15803d', ARRAY['check', 'success', 'icon'], ARRAY['check', 'tick', 'success'], 'Minimalist', 0),
('X Close', 'x-close', 'Close X icon', 'Icons', 'Actions', 'https://www.svgrepo.com/show/13671/close.svg', 'https://www.svgrepo.com/show/13671/close.svg', 'https://www.svgrepo.com/show/13671/close.svg', '0 0 512 512', 512, 512, false, false, true, '#ef4444', ARRAY['close', 'x', 'icon'], ARRAY['close', 'x', 'cancel'], 'Minimalist', 0),
('Arrow Right', 'arrow-right', 'Right pointing arrow', 'Icons', 'Navigation', 'https://www.svgrepo.com/show/13671/arrow-right.svg', 'https://www.svgrepo.com/show/13671/arrow-right.svg', 'https://www.svgrepo.com/show/13671/arrow-right.svg', '0 0 512 512', 512, 512, false, true, true, '#3b82f6', ARRAY['arrow', 'right', 'icon'], ARRAY['arrow', 'right', 'navigation'], 'Minimalist', 0),
('Location Pin', 'location-pin', 'Map location pin', 'Icons', 'Location', 'https://www.svgrepo.com/show/13671/location.svg', 'https://www.svgrepo.com/show/13671/location.svg', 'https://www.svgrepo.com/show/13671/location.svg', '0 0 512 512', 512, 512, false, true, true, '#ef4444', ARRAY['location', 'pin', 'map'], ARRAY['location', 'pin', 'place'], 'Modern', 0),
('Settings Gear', 'settings-gear', 'Settings gear icon', 'Icons', 'Settings', 'https://www.svgrepo.com/show/13671/settings.svg', 'https://www.svgrepo.com/show/13671/settings.svg', 'https://www.svgrepo.com/show/13671/settings.svg', '0 0 512 512', 512, 512, false, false, true, '#6b7280', ARRAY['settings', 'gear', 'icon'], ARRAY['settings', 'gear', 'config'], 'Minimalist', 0);

