#!/bin/bash
echo "🧪 Test de l'API Profile"
echo "========================"
echo ""
echo "Ce script teste si l'API profile fonctionne"
echo ""
echo "✅ Fichiers vérifiés:"
ls -la apps/frontend/src/app/api/profile/ 2>/dev/null || echo "❌ Dossier API profile non trouvé"
echo ""
echo "✅ Hooks vérifiés:"
ls -la apps/frontend/src/lib/hooks/useProfile.ts 2>/dev/null || echo "❌ Hook useProfile non trouvé"
echo ""
echo "📝 Pour tester l'API, ouvrez la console navigateur (F12) sur:"
echo "   https://app.luneo.app/settings"
echo ""
echo "Et vérifiez les requêtes réseau vers /api/profile"
