#!/bin/bash

# ===============================================
# COMMANDES DE DEPLOIEMENT MANUEL
# ===============================================
# Exécutez ces commandes une par une sur le serveur

echo "🚀 COMMANDES DE DEPLOIEMENT MANUEL LUNEO BACKEND"
echo "🌐 Connectez-vous au serveur: ssh root@116.203.31.129"
echo ""
echo "📋 Exécutez ces commandes dans l'ordre :"
echo ""

echo "1️⃣ Mise à jour du système :"
echo "apt update && apt upgrade -y"
echo ""

echo "2️⃣ Installation des packages :"
echo "apt install -y curl git ufw fail2ban docker.io docker-compose nginx certbot python3-certbot-nginx"
echo ""

echo "3️⃣ Configuration Docker :"
echo "systemctl enable docker && systemctl start docker"
echo ""

echo "4️⃣ Création de l'utilisateur deploy :"
echo "adduser --disabled-password --gecos '' deploy"
echo "usermod -aG sudo deploy"
echo "usermod -aG docker deploy"
echo ""

echo "5️⃣ Configuration du firewall :"
echo "ufw allow OpenSSH"
echo "ufw allow 80"
echo "ufw allow 443"
echo "ufw enable"
echo ""

echo "6️⃣ Configuration Fail2ban :"
echo "systemctl enable fail2ban && systemctl start fail2ban"
echo ""

echo "7️⃣ Configuration Nginx :"
echo "systemctl enable nginx && systemctl start nginx"
echo ""

echo "8️⃣ Configuration Nginx pour le domaine :"
echo "cat > /etc/nginx/sites-available/luneo.com.conf << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    server_name luneo.com *.luneo.com;"
echo "    return 301 https://\$host\$request_uri;"
echo "}"
echo ""
echo "server {"
echo "    listen 443 ssl http2;"
echo "    server_name luneo.com *.luneo.com;"
echo ""
echo "    ssl_certificate /etc/letsencrypt/live/luneo.com/fullchain.pem;"
echo "    ssl_certificate_key /etc/letsencrypt/live/luneo.com/privkey.pem;"
echo "    "
echo "    ssl_protocols TLSv1.2 TLSv1.3;"
echo "    ssl_prefer_server_ciphers off;"
echo "    ssl_session_cache shared:SSL:10m;"
echo "    ssl_session_timeout 10m;"
echo ""
echo "    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;"
echo "    add_header X-Frame-Options DENY always;"
echo "    add_header X-Content-Type-Options nosniff always;"
echo "    add_header X-XSS-Protection \"1; mode=block\" always;"
echo ""
echo "    location / {"
echo "        proxy_pass http://127.0.0.1:3000;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "        proxy_set_header X-Forwarded-Host \$host;"
echo "        proxy_set_header X-Forwarded-Port \$server_port;"
echo "        "
echo "        proxy_connect_timeout 60s;"
echo "        proxy_send_timeout 60s;"
echo "        proxy_read_timeout 60s;"
echo "        "
echo "        proxy_buffering on;"
echo "        proxy_buffer_size 4k;"
echo "        proxy_buffers 8 4k;"
echo "    }"
echo ""
echo "    location /health {"
echo "        proxy_pass http://127.0.0.1:3000/health;"
echo "        access_log off;"
echo "    }"
echo "}"
echo "EOF"
echo ""

echo "9️⃣ Activation du site Nginx :"
echo "ln -sf /etc/nginx/sites-available/luneo.com.conf /etc/nginx/sites-enabled/"
echo "rm -f /etc/nginx/sites-enabled/default"
echo "nginx -t && systemctl restart nginx"
echo ""

echo "🔟 Génération du certificat SSL :"
echo "certbot certonly --nginx -d luneo.com --agree-tos --no-eff-email -m emmanuel@luneo.app --non-interactive"
echo ""

echo "1️⃣1️⃣ Création du répertoire de l'application :"
echo "mkdir -p /home/deploy/luneo-backend/backend"
echo ""

echo "1️⃣2️⃣ Copie du code source (depuis votre machine locale) :"
echo "scp -r /path/to/your/backend/* deploy@116.203.31.129:/home/deploy/luneo-backend/backend/"
echo ""

echo "1️⃣3️⃣ Configuration Docker Compose :"
echo "cat > /home/deploy/luneo-backend/backend/docker-compose.yml << 'EOF'"
echo "version: \"3.9\""
echo ""
echo "services:"
echo "  api:"
echo "    build:"
echo "      context: ."
echo "      dockerfile: Dockerfile"
echo "      target: production"
echo "    container_name: luneo_api"
echo "    working_dir: /app"
echo "    volumes:"
echo "      - .:/app"
echo "      - /app/node_modules"
echo "    ports:"
echo "      - \"3000:3000\""
echo "    environment:"
echo "      - NODE_ENV=production"
echo "      - DATABASE_URL=postgresql://luneo_user:Luneo2024Secure!@db:5432/luneo_production?schema=public"
echo "      - REDIS_URL=redis://:Luneo2024Secure!@redis:6379"
echo "      - JWT_SECRET=Luneo2024SuperSecretJWTKey32Chars!"
echo "      - JWT_REFRESH_SECRET=Luneo2024SuperSecretRefreshKey32Chars!"
echo "      - SENDGRID_API_KEY=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"
echo "      - SENDGRID_DOMAIN=luneo.app"
echo "      - SENDGRID_FROM_NAME=Luneo"
echo "      - SENDGRID_FROM_EMAIL=no-reply@luneo.app"
echo "      - SMTP_HOST=smtp.sendgrid.net"
echo "      - SMTP_PORT=587"
echo "      - SMTP_SECURE=false"
echo "      - SMTP_FROM=Luneo <no-reply@luneo.app>"
echo "      - DOMAIN_VERIFIED=true"
echo "      - PORT=3000"
echo "      - API_PREFIX=/api/v1"
echo "      - CORS_ORIGIN=https://luneo.com"
echo "      - FRONTEND_URL=https://luneo.com"
echo "    command: >"
echo "      sh -c \\\""
echo "        npm install -g pnpm &&"
echo "        pnpm install --frozen-lockfile &&"
echo "        pnpm run build &&"
echo "        pnpm run start:prod"
echo "      \\\""
echo "    restart: unless-stopped"
echo "    depends_on:"
echo "      - db"
echo "      - redis"
echo "    networks:"
echo "      - luneo_network"
echo ""
echo "  db:"
echo "    image: postgres:15-alpine"
echo "    container_name: luneo_db"
echo "    environment:"
echo "      POSTGRES_USER: luneo_user"
echo "      POSTGRES_PASSWORD: Luneo2024Secure!"
echo "      POSTGRES_DB: luneo_production"
echo "    volumes:"
echo "      - db_data:/var/lib/postgresql/data"
echo "    restart: unless-stopped"
echo "    networks:"
echo "      - luneo_network"
echo ""
echo "  redis:"
echo "    image: redis:7-alpine"
echo "    container_name: luneo_redis"
echo "    command: redis-server --requirepass Luneo2024Secure!"
echo "    volumes:"
echo "      - redis_data:/data"
echo "    restart: unless-stopped"
echo "    networks:"
echo "      - luneo_network"
echo ""
echo "volumes:"
echo "  db_data:"
echo "  redis_data:"
echo ""
echo "networks:"
echo "  luneo_network:"
echo "    driver: bridge"
echo "EOF"
echo ""

echo "1️⃣4️⃣ Lancement de l'application :"
echo "cd /home/deploy/luneo-backend/backend"
echo "docker compose up -d --build"
echo ""

echo "1️⃣5️⃣ Installation de Watchtower :"
echo "docker run -d --name watchtower -v /var/run/docker.sock:/var/run/docker.sock --restart unless-stopped containrrr/watchtower --cleanup --interval 3600"
echo ""

echo "1️⃣6️⃣ Vérification :"
echo "docker compose ps"
echo "curl http://localhost:3000/health"
echo ""

echo "🎉 DÉPLOIEMENT TERMINÉ !"
echo "🌐 Votre API sera accessible sur: https://luneo.com/api/v1"
echo "🔗 Testez avec: curl https://luneo.com/api/v1/health"

