export const ORION_DEFAULTS = {
  LIST_LIMIT: 20,
  DASHBOARD_LIMIT: 10,
  ACTIVITY_FEED_LIMIT: 30,
  MAX_LIST_LIMIT: 100,
  AUDIT_DEFAULT_LIMIT: 50,
  TRAINING_DEFAULT_LIMIT: 50,
} as const;

export const PROMETHEUS_THRESHOLDS = {
  MIN_CONFIDENCE_FOR_AUTO_GENERATE: 30,
  AUTO_APPROVE_CONFIDENCE: 80,
  CONTEXT_MESSAGE_WEIGHT: 15,
  CONTEXT_BRAND_BONUS: 15,
  CONTEXT_CUSTOMER_BONUS: 20,
  KB_ARTICLE_WEIGHT: 25,
  RESPONSE_TOKEN_THRESHOLD: 100,
  RESPONSE_COMPLETE_SCORE: 80,
  RESPONSE_INCOMPLETE_SCORE: 40,
  CUSTOMER_HISTORY_HIGH: 90,
  CUSTOMER_HISTORY_MED: 60,
  CUSTOMER_HISTORY_LOW: 30,
  CUSTOMER_HISTORY_THRESHOLD: 3,
} as const;

export const ARTEMIS_THRESHOLDS = {
  BRUTE_FORCE_WINDOW_MS: 10 * 60 * 1000,
  BRUTE_FORCE_MIN_ATTEMPTS: 5,
  BRUTE_FORCE_CRITICAL_THRESHOLD: 10,
  SUSPICIOUS_LOGIN_WINDOW_MS: 60 * 60 * 1000,
  SUSPICIOUS_LOGIN_IP_THRESHOLD: 3,
  API_ABUSE_WINDOW_MS: 5 * 60 * 1000,
  API_ABUSE_THRESHOLD: 200,
  THREAT_DEDUP_WINDOW_MS: 30 * 60 * 1000,
  ONE_DAY_MS: 24 * 60 * 60 * 1000,
  SECURITY_SCORE_THREAT_PENALTY: 10,
  SECURITY_SCORE_FRAUD_PENALTY: 5,
  SECURITY_SCORE_BLOCKED_BONUS: 5,
} as const;

export const ATHENA_THRESHOLDS = {
  ENGAGEMENT_LOW: 30,
  SATISFACTION_LOW: 40,
  FINANCIAL_LOW: 30,
  ADOPTION_LOW: 20,
  SUPPORT_LOW: 30,
  INACTIVE_DAYS: 14,
} as const;

export const HADES_PLAN_PRICES: Record<string, number> = {
  FREE: 0,
  STARTER: 29,
  PROFESSIONAL: 79,
  BUSINESS: 199,
  ENTERPRISE: 499,
} as const;

export const ZEUS_THRESHOLDS = {
  CANCELLATION_ALERT_THRESHOLD: 5,
  CHURN_PERCENTAGE_ALERT: 0.2,
  SLA_BREACH_ALERT_THRESHOLD: 3,
  UNHEALTHY_SERVICES_CRITICAL: 2,
} as const;

export const SLA_DEFAULTS = {
  LOW_RESPONSE_MINUTES: 480,
  LOW_RESOLUTION_MINUTES: 2880,
  MEDIUM_RESPONSE_MINUTES: 240,
  MEDIUM_RESOLUTION_MINUTES: 1440,
  HIGH_RESPONSE_MINUTES: 60,
  HIGH_RESOLUTION_MINUTES: 480,
  URGENT_RESPONSE_MINUTES: 30,
  URGENT_RESOLUTION_MINUTES: 120,
} as const;

export interface OrionAgentActionData {
  suggestedAction?: string;
  userId?: string;
  factors?: string[];
  recommendedActions?: string[];
  churnRiskScore?: number;
  canceledCount?: number;
  atRisk?: number;
  total?: number;
  percentage?: number;
  breachedCount?: number;
  unhealthyServices?: number;
  [key: string]: unknown;
}

export interface AuditLogMetadata {
  ipAddress?: string;
  userAgent?: string;
  [key: string]: unknown;
}
