import type { PlanCatalog, PlanDefinition, PlanQuotaDefinition, PlanTier } from './types';

const BASE_THRESHOLDS = [50, 75, 90];

const quota = (
  definition: Omit<PlanQuotaDefinition, 'notificationThresholds'> & {
    notificationThresholds?: number[];
  },
): PlanQuotaDefinition => ({
  notificationThresholds: definition.notificationThresholds ?? BASE_THRESHOLDS,
  ...definition,
});

export const PLAN_DEFINITIONS: Record<PlanTier, PlanDefinition> = {
  starter: {
    id: 'starter',
    name: 'Starter',
    headline: 'Idéal pour les équipes qui démarrent',
    basePriceCents: 2_900,
    quotas: [
      quota({
        metric: 'designs_created',
        label: 'Designs générés',
        description: 'Nombre de designs générés via IA ou pipeline interne',
        limit: 50,
        period: 'month',
        overage: 'charge',
        overageRate: 50,
        unit: 'design',
      }),
      quota({
        metric: 'renders_2d',
        label: 'Rendus 2D',
        description: 'Rendus 2D haute résolution',
        limit: 100,
        period: 'month',
        overage: 'charge',
        overageRate: 20,
        unit: 'render',
        creditCost: 1, // 1 credit per 2D render
        baseCostCents: 20, // Base cost: 20 cents per render
      }),
      quota({
        metric: 'renders_3d',
        label: 'Rendus 3D',
        description: 'Rendus 3D/GLTF haute précision',
        limit: 10,
        period: 'month',
        overage: 'charge',
        overageRate: 100,
        unit: 'render',
        creditCost: 5, // 5 credits per 3D render
        baseCostCents: 100, // Base cost: 100 cents per render
      }),
      quota({
        metric: 'ai_generations',
        label: 'Générations IA',
        description: 'Générations IA via modèles internes et externes',
        limit: 20,
        period: 'month',
        overage: 'charge',
        overageRate: 75,
        unit: 'generation',
      }),
      quota({
        metric: 'storage_gb',
        label: 'Stockage',
        description: 'Stockage cloud pour assets (GB)',
        limit: 5,
        period: 'month',
        overage: 'charge',
        overageRate: 50,
        unit: 'gb',
      }),
      quota({
        metric: 'api_calls',
        label: 'Requêtes API',
        description: 'Appels API authentifiés',
        limit: 10_000,
        period: 'month',
        overage: 'charge',
        overageRate: 1,
        unit: 'call',
      }),
      quota({
        metric: 'team_members',
        label: 'Membres d’équipe',
        description: 'Collaborateurs actifs sur le workspace',
        limit: 3,
        period: 'month',
        overage: 'block',
        unit: 'seat',
      }),
    ],
    features: [
      {
        id: 'support.standard',
        label: 'Support standard',
        enabled: true,
      },
      {
        id: 'analytics.basic',
        label: 'Analytics de base',
        enabled: true,
      },
      {
        id: 'branding.custom',
        label: 'Branding personnalisé',
        enabled: false,
      },
      {
        id: 'api.access',
        label: 'Accès API',
        enabled: false,
      },
    ],
    limits: {
      designsPerMonth: 50,
      storageGb: 5,
      teamMembers: 3,
    },
  },
  professional: {
    id: 'professional',
    name: 'Professional',
    headline: 'Pour les équipes qui accélèrent',
    basePriceCents: 9_900,
    quotas: [
      quota({
        metric: 'designs_created',
        label: 'Designs générés',
        description: 'Nombre de designs générés via IA ou pipeline interne',
        limit: 250,
        period: 'month',
        overage: 'charge',
        overageRate: 30,
        unit: 'design',
      }),
      quota({
        metric: 'renders_2d',
        label: 'Rendus 2D',
        description: 'Rendus 2D haute résolution',
        limit: 500,
        period: 'month',
        overage: 'charge',
        overageRate: 15,
        unit: 'render',
        creditCost: 1,
        baseCostCents: 15,
      }),
      quota({
        metric: 'renders_3d',
        label: 'Rendus 3D',
        description: 'Rendus 3D haute précision',
        limit: 50,
        period: 'month',
        overage: 'charge',
        overageRate: 80,
        unit: 'render',
        creditCost: 5,
        baseCostCents: 80,
      }),
      quota({
        metric: 'ai_generations',
        label: 'Générations IA',
        description: 'Générations IA via modèles internes et externes',
        limit: 150,
        period: 'month',
        overage: 'charge',
        overageRate: 50,
        unit: 'generation',
      }),
      quota({
        metric: 'storage_gb',
        label: 'Stockage',
        description: 'Stockage cloud pour assets (GB)',
        limit: 50,
        period: 'month',
        overage: 'charge',
        overageRate: 30,
        unit: 'gb',
      }),
      quota({
        metric: 'api_calls',
        label: 'Requêtes API',
        description: 'Appels API authentifiés',
        limit: 100_000,
        period: 'month',
        overage: 'charge',
        overageRate: 1,
        unit: 'call',
      }),
      quota({
        metric: 'team_members',
        label: 'Membres d’équipe',
        description: 'Collaborateurs actifs sur le workspace',
        limit: 10,
        period: 'month',
        overage: 'block',
        unit: 'seat',
      }),
    ],
    features: [
      {
        id: 'support.priority',
        label: 'Support prioritaire',
        enabled: true,
      },
      {
        id: 'analytics.advanced',
        label: 'Analytics avancés',
        enabled: true,
      },
      {
        id: 'branding.custom',
        label: 'Branding personnalisé',
        enabled: true,
      },
      {
        id: 'api.access',
        label: 'Accès API',
        enabled: true,
      },
      {
        id: 'webhooks',
        label: 'Webhooks temps réel',
        enabled: true,
      },
    ],
    limits: {
      designsPerMonth: 250,
      storageGb: 50,
      teamMembers: 10,
    },
  },
  business: {
    id: 'business',
    name: 'Business',
    headline: 'Scale-up et équipes internationales',
    basePriceCents: 29_900,
    quotas: [
      quota({
        metric: 'designs_created',
        label: 'Designs générés',
        description: 'Nombre de designs générés via IA ou pipeline interne',
        limit: 1_000,
        period: 'month',
        overage: 'charge',
        overageRate: 30,
        unit: 'design',
      }),
      quota({
        metric: 'renders_2d',
        label: 'Rendus 2D',
        description: 'Rendus 2D haute résolution',
        limit: 2_000,
        period: 'month',
        overage: 'charge',
        overageRate: 10,
        unit: 'render',
        creditCost: 1,
        baseCostCents: 10,
      }),
      quota({
        metric: 'renders_3d',
        label: 'Rendus 3D',
        description: 'Rendus 3D/GLTF haute précision',
        limit: 200,
        period: 'month',
        overage: 'charge',
        overageRate: 60,
        unit: 'render',
        creditCost: 5,
        baseCostCents: 60,
      }),
      quota({
        metric: 'ai_generations',
        label: 'Générations IA',
        description: 'Générations IA via modèles internes et externes',
        limit: 500,
        period: 'month',
        overage: 'charge',
        overageRate: 40,
        unit: 'generation',
      }),
      quota({
        metric: 'storage_gb',
        label: 'Stockage',
        description: 'Stockage cloud pour assets (GB)',
        limit: 100,
        period: 'month',
        overage: 'charge',
        overageRate: 20,
        unit: 'gb',
      }),
      quota({
        metric: 'api_calls',
        label: 'Requêtes API',
        description: 'Appels API authentifiés',
        limit: 200_000,
        period: 'month',
        overage: 'charge',
        overageRate: 1,
        unit: 'call',
      }),
      quota({
        metric: 'team_members',
        label: 'Membres d’équipe',
        description: 'Collaborateurs actifs sur le workspace',
        limit: 50,
        period: 'month',
        overage: 'block',
        unit: 'seat',
      }),
    ],
    features: [
      {
        id: 'support.dedicated',
        label: 'Support dédié',
        enabled: true,
      },
      {
        id: 'analytics.advanced',
        label: 'Analytics avancés',
        enabled: true,
      },
      {
        id: 'branding.full',
        label: 'Branding complet et white-label',
        enabled: true,
      },
      {
        id: 'api.access',
        label: 'Accès API & SDKs',
        enabled: true,
      },
      {
        id: 'compliance.sla',
        label: 'SLA 99.5% & conformité renforcée',
        enabled: true,
      },
    ],
    addons: [
      {
        id: 'addon.custom_domains',
        label: 'Domaines personnalisés supplémentaires',
        description: 'Domaines additionnels pour portails clients',
        priceCents: 2_000,
        meteredMetric: 'custom_domains',
      },
      {
        id: 'addon.additional_members',
        label: 'Membres équipe supplémentaires',
        description: 'Pack de 10 sièges supplémentaires',
        priceCents: 4_500,
        meteredMetric: 'team_members',
      },
    ],
    limits: {
      designsPerMonth: 1_000,
      storageGb: 100,
      teamMembers: 50,
    },
  },
  enterprise: {
    id: 'enterprise',
    name: 'Enterprise',
    headline: 'Programmes sur-mesure & multi-division',
    basePriceCents: 99_900,
    quotas: [
      quota({
        metric: 'designs_created',
        label: 'Designs générés',
        description: 'Illimité avec politiques personnalisées',
        limit: 99_999,
        period: 'month',
        overage: 'charge',
        overageRate: 20,
        unit: 'design',
      }),
      quota({
        metric: 'renders_2d',
        label: 'Rendus 2D',
        description: 'Rendus 2D haute résolution',
        limit: 99_999,
        period: 'month',
        overage: 'charge',
        overageRate: 5,
        unit: 'render',
        creditCost: 1,
        baseCostCents: 5,
      }),
      quota({
        metric: 'renders_3d',
        label: 'Rendus 3D',
        description: 'Rendus 3D/GLTF haute précision',
        limit: 99_999,
        period: 'month',
        overage: 'charge',
        overageRate: 40,
        unit: 'render',
        creditCost: 5,
        baseCostCents: 40,
      }),
      quota({
        metric: 'ai_generations',
        label: 'Générations IA',
        description: 'Générations IA via modèles internes et externes',
        limit: 99_999,
        period: 'month',
        overage: 'charge',
        overageRate: 40,
        unit: 'generation',
      }),
      quota({
        metric: 'storage_gb',
        label: 'Stockage',
        description: 'Stockage cloud pour assets (GB)',
        limit: 500,
        period: 'month',
        overage: 'charge',
        overageRate: 20,
        unit: 'gb',
      }),
      quota({
        metric: 'api_calls',
        label: 'Requêtes API',
        description: 'Appels API authentifiés',
        limit: 9_999_999,
        period: 'month',
        overage: 'charge',
        overageRate: 1,
        unit: 'call',
      }),
      quota({
        metric: 'team_members',
        label: 'Membres d’équipe',
        description: 'Collaborateurs actifs sur le workspace',
        limit: 999,
        period: 'month',
        overage: 'block',
        unit: 'seat',
      }),
    ],
    features: [
      {
        id: 'support.white_glove',
        label: 'Support white-glove 24/7',
        enabled: true,
      },
      {
        id: 'analytics.custom',
        label: 'Analytics personnalisés & BI',
        enabled: true,
      },
      {
        id: 'infrastructure.dedicated',
        label: 'Infrastructure dédiée multi-régions',
        enabled: true,
      },
      {
        id: 'compliance.enterprise',
        label: 'Compliance avancée & audits',
        enabled: true,
      },
      {
        id: 'training.enablement',
        label: 'Programmes d’onboarding & formation',
        enabled: true,
      },
    ],
    addons: [
      {
        id: 'addon.sla',
        label: 'SLA 99.9% contractuel',
        description: 'Engagement contractuel SLA, support multi-canal',
        priceCents: 7_500,
      },
      {
        id: 'addon.regional_clusters',
        label: 'Clusters régionaux supplémentaires',
        description: 'Déploiements supplémentaires en multi-régions',
      },
    ],
    limits: {
      designsPerMonth: 99_999,
      storageGb: 500,
      teamMembers: 999,
    },
  },
};

export const PLAN_CATALOG: PlanCatalog = {
  plans: PLAN_DEFINITIONS,
  defaultPlan: 'starter',
  availableTiers: ['starter', 'professional', 'business', 'enterprise'],
};

export function getPlanDefinition(plan: PlanTier): PlanDefinition {
  return PLAN_DEFINITIONS[plan];
}

export function listPlans(): PlanDefinition[] {
  return Object.values(PLAN_DEFINITIONS);
}

