'use client'; import React from 'react';
import { DocPageTemplate } from '@/components/docs/DocPageTemplate';
import { Card } from '@/components/ui/card';
import { Code, Copy } from 'lucide-react';
import { Button } from '@/components/ui/button'; export default function StripeIntegrationPage() { const exampleCode = `// Configuration Stripe
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY); // Créer un Payment Intent après génération du design
const paymentIntent = await stripe.paymentIntents.create({ amount: 2999, // 29.99 EUR en centimes currency: 'eur', metadata: { designId: 'dsg_123', orderId: 'ord_456' }
});`; return ( <DocPageTemplate title="Intégration Stripe" description="Intégrez Stripe pour gérer les paiements de vos designs personnalisés" breadcrumbs={[ { label: 'Documentation', href: '/help/documentation' }, { label: 'Intégrations', href: '/help/documentation/integrations' }, { label: 'Stripe', href: '/help/documentation/integrations/stripe' } ]} relatedLinks={[ { title: 'Webhooks', href: '/help/documentation/api-reference/webhooks', description: 'Configurer les webhooks Stripe' }, { title: 'Facturation', href: '/billing', description: 'Gérer vos abonnements' } ]} > <h2 className="text-xl sm:text-lg sm:text-xl md:text-2xl md:text-xl sm:text-lg sm:text-xl md:text-2xl md:text-lg sm:text-xl md:text-2xl lg:text-xl sm:text-2xl md:text-base min-[480px]:text-lg sm:text-xl md:text-base min-[480px]:text-lg sm:text-xl md:text-2xl lg:text-lg sm:text-xl md:text-2xl lg:text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold mt-8 mb-4">Configuration</h2> <p className="text-gray-300 mb-6"> Luneo utilise Stripe pour gérer tous les paiements de manière sécurisée. Aucune donnée bancaire n'est stockée sur nos serveurs. </p> <Card className="bg-gray-800 border-gray-700 p-6 my-8"> <div className="flex flex-col sm:flex-row items-center justify-start sm:justify-between gap-3 sm:gap-0 mb-4"> <h3 className="text-lg font-semibold flex items-center"> <Code className="w-5 h-5 mr-2" /> Exemple d'intégration </h3> <Button variant="outline" size="sm" className="border-green-500 text-green-400 hover:bg-green-500 hover:text-white"> <Copy className="w-4 h-4 mr-2" /> Copier </Button> </div> <pre className="bg-gray-900 rounded p-4 overflow-x-autooverflow-x-autooverflow-x-auto"> <code className="text-sm text-gray-300">{exampleCode}</code> </pre> </Card> <h2 className="text-xl sm:text-lg sm:text-xl md:text-2xl md:text-xl sm:text-lg sm:text-xl md:text-2xl md:text-lg sm:text-xl md:text-2xl lg:text-xl sm:text-2xl md:text-base min-[480px]:text-lg sm:text-xl md:text-base min-[480px]:text-lg sm:text-xl md:text-2xl lg:text-lg sm:text-xl md:text-2xl lg:text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold mt-8 mb-4">Fonctionnalités</h2> <ul className="space-y-2 text-gray-300"> <li>✅ Paiements sécurisés PCI-DSS</li> <li>✅ Support multi-devises</li> <li>✅ Abonnements récurrents</li> <li>✅ Essais gratuits (14 jours)</li> <li>✅ Webhooks en temps réel</li> </ul> </DocPageTemplate> );
}
